from principal.models import Empleados,Almacen,Zapato,Series,numeroSeries,Genero,Color,Marca,Persona,Cabecera,Detalle,Tipo,Noticia
from django.contrib import admin
admin.site.register(Empleados)
admin.site.register(Almacen)
admin.site.register(Zapato)
admin.site.register(Series)
admin.site.register(Genero)
admin.site.register(Color)
admin.site.register(Marca)
admin.site.register(Persona)
admin.site.register(Cabecera)
admin.site.register(Detalle)
admin.site.register(numeroSeries)
admin.site.register(Tipo)
admin.site.register(Noticia)
